#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_CONSOLECURSORINFO_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_CONSOLECURSORINFO_H_

struct NtConsoleCursorInfo {
  uint32_t dwSize;
  bool32 bVisible;
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_CONSOLECURSORINFO_H_ */
