#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_EXCEPTIONFRAME_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_EXCEPTIONFRAME_H_

struct NtExceptionFrame {
  struct NtExceptionFrame *Prev;
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_EXCEPTIONFRAME_H_ */
