#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_FILEINTERNALINFORMATION_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_FILEINTERNALINFORMATION_H_

struct NtFileInternalInformation {
  int64_t IndexNumber;
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_FILEINTERNALINFORMATION_H_ */
