#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_FILEEAINFORMATION_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_FILEEAINFORMATION_H_

struct NtFileEaInformation {
  uint32_t EaSize;
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_FILEEAINFORMATION_H_ */
