#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_FILEMODEINFORMATION_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_FILEMODEINFORMATION_H_

struct NtFileModeInformation {
  uint32_t Mode;
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_FILEMODEINFORMATION_H_ */
