#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_FILEPOSITIONINFORMATION_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_FILEPOSITIONINFORMATION_H_

struct NtFilePositionInformation {
  int64_t CurrentByteOffset;
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_FILEPOSITIONINFORMATION_H_ */
