#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_FILEACCESSINFORMATION_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_FILEACCESSINFORMATION_H_

struct NtFileAccessInformation {
  uint32_t AccessFlags;
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_FILEACCESSINFORMATION_H_ */
