#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_FILENAMEINFORMATION_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_FILENAMEINFORMATION_H_

struct NtFileNameInformation {
  uint32_t FileNameLength;
  char16_t FileName[1];
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_FILENAMEINFORMATION_H_ */
