#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEDATADIRECTORY_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEDATADIRECTORY_H_
#if !(__ASSEMBLER__ + __LINKER__ + 0)

struct NtImageDataDirectory {
  uint32_t VirtualAddress;
  uint32_t Size;
};

#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEDATADIRECTORY_H_ */
