#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_IMAGERESOURCEDIRSTRING_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_IMAGERESOURCEDIRSTRING_H_
#if !(__ASSEMBLER__ + __LINKER__ + 0)

struct NtImageResourceDirString {
  uint16_t Length;
  char16_t NameString[1];
};

#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_IMAGERESOURCEDIRSTRING_H_ */
