#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEPROLOGUEDYNAMICRELOCATIONHEADER_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEPROLOGUEDYNAMICRELOCATIONHEADER_H_
#if !(__ASSEMBLER__ + __LINKER__ + 0)

struct NtImagePrologueDynamicRelocationHeader {
  uint8_t PrologueByteCount;
  uint8_t PrologueBytes[0];
};

#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEPROLOGUEDYNAMICRELOCATIONHEADER_H_ \
        */
