#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEHOTPATCHHASHES_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEHOTPATCHHASHES_H_

struct NtImageHotPatchHashes {
  uint8_t SHA256[32];
  uint8_t SHA1[20];
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEHOTPATCHHASHES_H_ */
