#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEPROLOGUEDYNAMICRELOCATIONHEADER_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEPROLOGUEDYNAMICRELOCATIONHEADER_H_

struct NtImagePrologueDynamicRelocationHeader {
  uint8_t PrologueByteCount;
  uint8_t PrologueBytes[0];
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEPROLOGUEDYNAMICRELOCATIONHEADER_H_ \
        */
