#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEDATADIRECTORY_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEDATADIRECTORY_H_

struct NtImageDataDirectory {
  uint32_t VirtualAddress;
  uint32_t Size;
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEDATADIRECTORY_H_ */
