#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_IMAGERESOURCEDIRSTRING_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_IMAGERESOURCEDIRSTRING_H_

struct NtImageResourceDirString {
  uint16_t Length;
  char16_t NameString[1];
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_IMAGERESOURCEDIRSTRING_H_ */
