#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEIMPORTBYNAME_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEIMPORTBYNAME_H_

struct NtImageImportByName {
  uint16_t Hint;
  char Name[1];
};

#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_IMAGEIMPORTBYNAME_H_ */
