#ifndef COSMOPOLITAN_LIBC_NT_STRUCT_SIZE_H_
#define COSMOPOLITAN_LIBC_NT_STRUCT_SIZE_H_
COSMOPOLITAN_C_START_

struct NtSize {
  int32_t cx;
  int32_t cy;
};

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_NT_STRUCT_SIZE_H_ */
