#ifndef COSMOPOLITAN_LIBC_COMPAT_OPENBSD_H_
#define COSMOPOLITAN_LIBC_COMPAT_OPENBSD_H_
COSMOPOLITAN_C_START_

typedef unsigned char u_char;

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_COMPAT_OPENBSD_H_ */
