/*-*- mode:unix-assembly; indent-tabs-mode:t; tab-width:8; coding:utf-8     -*-│
│vi: set et ft=asm ts=8 tw=8 fenc=utf-8                                     :vi│
╞══════════════════════════════════════════════════════════════════════════════╡
│ Copyright 2020 Justine Alexandra Roberts Tunney                              │
│                                                                              │
│ Permission to use, copy, modify, and/or distribute this software for         │
│ any purpose with or without fee is hereby granted, provided that the         │
│ above copyright notice and this permission notice appear in all copies.      │
│                                                                              │
│ THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL                │
│ WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED                │
│ WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE             │
│ AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL         │
│ DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR        │
│ PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER               │
│ TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR             │
│ PERFORMANCE OF THIS SOFTWARE.                                                │
╚─────────────────────────────────────────────────────────────────────────────*/

/	TODO(jart): FIX ME

	.globl	"o//net/http/uricspn.c"
	.equ	"o//net/http/uricspn.c",.
	.globl	"o//net/http/uriparse.c"
	.equ	"o//net/http/uriparse.c",.

	.globl	"o/rel/net/http/uricspn.c"
	.equ	"o/rel/net/http/uricspn.c",.
	.globl	"o/rel/net/http/uriparse.c"
	.equ	"o/rel/net/http/uriparse.c",.

	.globl	"o/tiny/net/http/uricspn.c"
	.equ	"o/tiny/net/http/uricspn.c",.
	.globl	"o/tiny/net/http/uriparse.c"
	.equ	"o/tiny/net/http/uriparse.c",.

	.globl	"o/dbg/net/http/uricspn.c"
	.equ	"o/dbg/net/http/uricspn.c",.
	.globl	"o/dbg/net/http/uriparse.c"
	.equ	"o/dbg/net/http/uriparse.c",.

	.globl	"o/opt/net/http/uricspn.c"
	.equ	"o/opt/net/http/uricspn.c",.
	.globl	"o/opt/net/http/uriparse.c"
	.equ	"o/opt/net/http/uriparse.c",.

	.globl	"o/ansi/net/http/uricspn.c"
	.equ	"o/ansi/net/http/uricspn.c",.
	.globl	"o/ansi/net/http/uriparse.c"
	.equ	"o/ansi/net/http/uriparse.c",.
