/*-*- mode:asm; indent-tabs-mode:t; tab-width:8; coding:utf-8               -*-│
│vi: set et ft=asm ts=8 tw=8 fenc=utf-8                                     :vi│
╞══════════════════════════════════════════════════════════════════════════════╡
│ Copyright 2020 Justine Alexandra Roberts Tunney                              │
│                                                                              │
│ This program is free software; you can redistribute it and/or modify         │
│ it under the terms of the GNU General Public License as published by         │
│ the Free Software Foundation; version 2 of the License.                      │
│                                                                              │
│ This program is distributed in the hope that it will be useful, but          │
│ WITHOUT ANY WARRANTY; without even the implied warranty of                   │
│ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU             │
│ General Public License for more details.                                     │
│                                                                              │
│ You should have received a copy of the GNU General Public License            │
│ along with this program; if not, write to the Free Software                  │
│ Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA                │
│ 02110-1301 USA                                                               │
╚─────────────────────────────────────────────────────────────────────────────*/

/	TODO(jart): FIX ME

	.globl	"o//net/http/uricspn.c"
	.equ	"o//net/http/uricspn.c",.
	.globl	"o//net/http/uriparse.c"
	.equ	"o//net/http/uriparse.c",.

	.globl	"o/rel/net/http/uricspn.c"
	.equ	"o/rel/net/http/uricspn.c",.
	.globl	"o/rel/net/http/uriparse.c"
	.equ	"o/rel/net/http/uriparse.c",.

	.globl	"o/tiny/net/http/uricspn.c"
	.equ	"o/tiny/net/http/uricspn.c",.
	.globl	"o/tiny/net/http/uriparse.c"
	.equ	"o/tiny/net/http/uriparse.c",.

	.globl	"o/dbg/net/http/uricspn.c"
	.equ	"o/dbg/net/http/uricspn.c",.
	.globl	"o/dbg/net/http/uriparse.c"
	.equ	"o/dbg/net/http/uriparse.c",.

	.globl	"o/opt/net/http/uricspn.c"
	.equ	"o/opt/net/http/uricspn.c",.
	.globl	"o/opt/net/http/uriparse.c"
	.equ	"o/opt/net/http/uriparse.c",.

	.globl	"o/ansi/net/http/uricspn.c"
	.equ	"o/ansi/net/http/uricspn.c",.
	.globl	"o/ansi/net/http/uriparse.c"
	.equ	"o/ansi/net/http/uriparse.c",.
