#ifndef COSMOPOLITAN_LIBC_INTRIN_TIMELOG_H_
#define COSMOPOLITAN_LIBC_INTRIN_TIMELOG_H_
COSMOPOLITAN_C_START_

void timelog1(void);
void timelog(const char *);

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_INTRIN_TIMELOG_H_ */
