#ifndef COSMOPOLITAN_LIBC_INTRIN_UBSAN_H_
#define COSMOPOLITAN_LIBC_INTRIN_UBSAN_H_
COSMOPOLITAN_C_START_

extern bool32 __ubsan_strict;

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_INTRIN_UBSAN_H_ */
