#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_ALG_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_ALG_H_

#define ALG_SET_AEAD_ASSOCLEN ALG_SET_AEAD_ASSOCLEN
#define ALG_SET_AEAD_AUTHSIZE ALG_SET_AEAD_AUTHSIZE
#define ALG_SET_DRBG_ENTROPY  ALG_SET_DRBG_ENTROPY
#define ALG_SET_IV            ALG_SET_IV
#define ALG_SET_KEY           ALG_SET_KEY
#define ALG_SET_OP            ALG_SET_OP

#define ALG_OP_DECRYPT ALG_OP_DECRYPT
#define ALG_OP_ENCRYPT ALG_OP_ENCRYPT

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const int ALG_SET_AEAD_ASSOCLEN;
extern const int ALG_SET_AEAD_AUTHSIZE;
extern const int ALG_SET_DRBG_ENTROPY;
extern const int ALG_SET_IV;
extern const int ALG_SET_KEY;
extern const int ALG_SET_OP;

extern const int ALG_OP_DECRYPT;
extern const int ALG_OP_ENCRYPT;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_ALG_H_ */
