#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_ARCH_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_ARCH_H_

#define ARCH_SET_GS 0x1001
#define ARCH_SET_FS 0x1002
#define ARCH_GET_FS 0x1003
#define ARCH_GET_GS 0x1004

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_ARCH_H_ */
