#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_ARPHRD_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_ARPHRD_H_

#define ARPHRD_ETHER ARPHRD_ETHER
#define ARPHRD_FCFABRIC ARPHRD_FCFABRIC
#define ARPHRD_IEEE80211 ARPHRD_IEEE80211
#define ARPHRD_IEEE80211_PRISM ARPHRD_IEEE80211_PRISM
#define ARPHRD_IEEE80211_RADIOTAP ARPHRD_IEEE80211_RADIOTAP
#define ARPHRD_IEEE802154 ARPHRD_IEEE802154
#define ARPHRD_IEEE802_TR ARPHRD_IEEE802_TR
#define ARPHRD_LOCALTLK ARPHRD_LOCALTLK

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const uint16_t ARPHRD_ETHER;
extern const uint16_t ARPHRD_FCFABRIC;
extern const uint16_t ARPHRD_IEEE80211;
extern const uint16_t ARPHRD_IEEE80211_PRISM;
extern const uint16_t ARPHRD_IEEE80211_RADIOTAP;
extern const uint16_t ARPHRD_IEEE802154;
extern const uint16_t ARPHRD_IEEE802_TR;
extern const uint16_t ARPHRD_LOCALTLK;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_ARPHRD_H_ */
