#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_BLK_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_BLK_H_
#include "libc/runtime/symbolic.h"

#define BLK_BYTECOUNT SYMBOLIC(BLK_BYTECOUNT)
#define BLK_EOF SYMBOLIC(BLK_EOF)
#define BLK_EOR SYMBOLIC(BLK_EOR)
#define BLK_ERRORS SYMBOLIC(BLK_ERRORS)
#define BLK_RESTART SYMBOLIC(BLK_RESTART)

#define BLKBSZGET SYMBOLIC(BLKBSZGET)
#define BLKBSZSET SYMBOLIC(BLKBSZSET)
#define BLKFLSBUF SYMBOLIC(BLKFLSBUF)
#define BLKFRAGET SYMBOLIC(BLKFRAGET)
#define BLKFRASET SYMBOLIC(BLKFRASET)
#define BLKGETSIZE SYMBOLIC(BLKGETSIZE)
#define BLKGETSIZE64 SYMBOLIC(BLKGETSIZE64)
#define BLKRAGET SYMBOLIC(BLKRAGET)
#define BLKRASET SYMBOLIC(BLKRASET)
#define BLKROGET SYMBOLIC(BLKROGET)
#define BLKROSET SYMBOLIC(BLKROSET)
#define BLKRRPART SYMBOLIC(BLKRRPART)
#define BLKSECTGET SYMBOLIC(BLKSECTGET)
#define BLKSECTSET SYMBOLIC(BLKSECTSET)
#define BLKSSZGET SYMBOLIC(BLKSSZGET)
#define BLKTYPE SYMBOLIC(BLKTYPE)

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const long BLK_BYTECOUNT;
extern const long BLK_EOF;
extern const long BLK_EOR;
extern const long BLK_ERRORS;
extern const long BLK_RESTART;

extern const long BLKBSZGET;
extern const long BLKBSZSET;
extern const long BLKFLSBUF;
extern const long BLKFRAGET;
extern const long BLKFRASET;
extern const long BLKGETSIZE64;
extern const long BLKGETSIZE;
extern const long BLKRAGET;
extern const long BLKRASET;
extern const long BLKROGET;
extern const long BLKROSET;
extern const long BLKRRPART;
extern const long BLKSECTGET;
extern const long BLKSECTSET;
extern const long BLKSSZGET;
extern const long BLKTYPE;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_BLK_H_ */
