#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_CLOCK_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_CLOCK_H_
COSMOPOLITAN_C_START_

extern int CLOCK_REALTIME_COARSE;
extern const int CLOCK_MONOTONIC;
extern int CLOCK_MONOTONIC_RAW;
extern int CLOCK_MONOTONIC_COARSE;
extern const int CLOCK_THREAD_CPUTIME_ID;
extern const int CLOCK_PROCESS_CPUTIME_ID;
extern const int CLOCK_BOOTTIME;

COSMOPOLITAN_C_END_

#define CLOCK_REALTIME        0
#define CLOCK_REALTIME_COARSE CLOCK_REALTIME_COARSE

#define CLOCK_MONOTONIC        CLOCK_MONOTONIC
#define CLOCK_MONOTONIC_RAW    CLOCK_MONOTONIC_RAW
#define CLOCK_MONOTONIC_COARSE CLOCK_MONOTONIC_COARSE

#define CLOCK_THREAD_CPUTIME_ID  CLOCK_THREAD_CPUTIME_ID
#define CLOCK_PROCESS_CPUTIME_ID CLOCK_PROCESS_CPUTIME_ID

#define CLOCK_BOOTTIME CLOCK_BOOTTIME

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_CLOCK_H_ */
