#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_CLOSE_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_CLOSE_H_
COSMOPOLITAN_C_START_

extern const unsigned int CLOSE_RANGE_UNSHARE;
extern const unsigned int CLOSE_RANGE_CLOEXEC;

COSMOPOLITAN_C_END_

#define CLOSE_RANGE_UNSHARE CLOSE_RANGE_UNSHARE
#define CLOSE_RANGE_CLOEXEC CLOSE_RANGE_CLOEXEC

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_CLOSE_H_ */
