#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_ENDIAN_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_ENDIAN_H_

#define __LITTLE_ENDIAN __ORDER_LITTLE_ENDIAN__
#define __BIG_ENDIAN    __ORDER_BIG_ENDIAN__
#define __PDP_ENDIAN    __ORDER_PDP_ENDIAN__
#define __BYTE_ORDER    __BYTE_ORDER__

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_ENDIAN_H_ */
