#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_EPOLL_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_EPOLL_H_
#include "libc/sysv/consts/o.h"

#define EPOLL_CTL_ADD 1
#define EPOLL_CTL_DEL 2
#define EPOLL_CTL_MOD 3

#define EPOLLIN        1
#define EPOLLPRI       2
#define EPOLLOUT       4
#define EPOLLERR       8
#define EPOLLHUP       0x10
#define EPOLLRDNORM    0x40
#define EPOLLRDBAND    0x80
#define EPOLLWRNORM    0x0100
#define EPOLLWRBAND    0x0200
#define EPOLLMSG       0x0400
#define EPOLLRDHUP     0x2000
#define EPOLLEXCLUSIVE 0x10000000
#define EPOLLWAKEUP    0x20000000
#define EPOLLONESHOT   0x40000000
#define EPOLLET        0x80000000

COSMOPOLITAN_C_START_

extern const int EPOLL_CLOEXEC;
#define EPOLL_CLOEXEC O_CLOEXEC

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_EPOLL_H_ */
