#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_FB_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_FB_H_
#include "libc/runtime/symbolic.h"
#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const uint64_t FBIOGET_VSCREENINFO;
extern const uint64_t FBIOPUT_VSCREENINFO;
extern const uint64_t FBIOGET_FSCREENINFO;
extern const uint64_t FBIOGETCMAP;
extern const uint64_t FBIOPUTCMAP;
extern const uint64_t FBIOPAN_DISPLAY;
extern const uint64_t FBIO_WAITFORVSYNC;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */

#define FBIOGET_VSCREENINFO SYMBOLIC(FBIOGET_VSCREENINFO)
#define FBIOPUT_VSCREENINFO SYMBOLIC(FBIOPUT_VSCREENINFO)
#define FBIOGET_FSCREENINFO SYMBOLIC(FBIOGET_FSCREENINFO)
#define FBIOGETCMAP         SYMBOLIC(FBIOGETCMAP)
#define FBIOPUTCMAP         SYMBOLIC(FBIOPUTCMAP)
#define FBIOPAN_DISPLAY     SYMBOLIC(FBIOPAN_DISPLAY)
#define FBIO_WAITFORVSYNC   SYMBOLIC(FBIO_WAITFORVSYNC)

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_FB_H_ */
