#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_FD_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_FD_H_
COSMOPOLITAN_C_START_

extern const int FD_CLOEXEC;

#define FD_CLOEXEC 1

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_FD_H_ */
