#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_FILENO_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_FILENO_H_
#include "libc/runtime/symbolic.h"

#define STDIN_FILENO LITERALLY(0)
#define STDOUT_FILENO LITERALLY(1)
#define STDERR_FILENO LITERALLY(2)

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_FILENO_H_ */
