#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_FILENO_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_FILENO_H_

#define STDIN_FILENO 0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_FILENO_H_ */
