#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_FUTEX_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_FUTEX_H_
#include "libc/runtime/symbolic.h"

#define FUTEX_PRIVATE_FLAG SYMBOLIC(FUTEX_PRIVATE_FLAG)
#define FUTEX_REQUEUE SYMBOLIC(FUTEX_REQUEUE)
#define FUTEX_REQUEUE_PRIVATE SYMBOLIC(FUTEX_REQUEUE_PRIVATE)
#define FUTEX_WAIT SYMBOLIC(FUTEX_WAIT)
#define FUTEX_WAIT_PRIVATE SYMBOLIC(FUTEX_WAIT_PRIVATE)
#define FUTEX_WAKE SYMBOLIC(FUTEX_WAKE)
#define FUTEX_WAKE_PRIVATE SYMBOLIC(FUTEX_WAKE_PRIVATE)

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

hidden extern const long FUTEX_PRIVATE_FLAG;
hidden extern const long FUTEX_REQUEUE;
hidden extern const long FUTEX_REQUEUE_PRIVATE;
hidden extern const long FUTEX_WAIT;
hidden extern const long FUTEX_WAIT_PRIVATE;
hidden extern const long FUTEX_WAKE;
hidden extern const long FUTEX_WAKE_PRIVATE;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_FUTEX_H_ */
