#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_GRND_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_GRND_H_
#include "libc/runtime/symbolic.h"

#define GRND_NONBLOCK LITERALLY(1)
#define GRND_RANDOM LITERALLY(2)

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_GRND_H_ */
