#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_IOV_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_IOV_H_
COSMOPOLITAN_C_START_

extern const int IOV_MAX;

COSMOPOLITAN_C_END_

#define IOV_MAX IOV_MAX

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_IOV_H_ */
