#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_IPPROTO_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_IPPROTO_H_

#define IPPROTO_IP     0
#define IPPROTO_ICMP   1
#define IPPROTO_TCP    6
#define IPPROTO_UDP    17
#define IPPROTO_IPV6   41
#define IPPROTO_ICMPV6 58
#define IPPROTO_RAW    255
#define IPPROTO_MAX    263 /* xxx */

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_IPPROTO_H_ */
