#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_IPV6_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_IPV6_H_
COSMOPOLITAN_C_START_

extern const int IPV6_V6ONLY;
extern const int IPV6_CHECKSUM;
extern const int IPV6_JOIN_GROUP;
extern const int IPV6_LEAVE_GROUP;
extern const int IPV6_MULTICAST_HOPS;
extern const int IPV6_MULTICAST_IF;
extern const int IPV6_MULTICAST_LOOP;
extern const int IPV6_UNICAST_HOPS;
extern const int IPV6_RECVTCLASS;
extern const int IPV6_TCLASS;
extern const int IPV6_DONTFRAG;
extern const int IPV6_HOPLIMIT;
extern const int IPV6_HOPOPTS;
extern const int IPV6_PKTINFO;
extern const int IPV6_RECVRTHDR;
extern const int IPV6_RTHDR;

#define IPV6_V6ONLY         IPV6_V6ONLY
#define IPV6_CHECKSUM       IPV6_CHECKSUM
#define IPV6_JOIN_GROUP     IPV6_JOIN_GROUP
#define IPV6_LEAVE_GROUP    IPV6_LEAVE_GROUP
#define IPV6_MULTICAST_HOPS IPV6_MULTICAST_HOPS
#define IPV6_MULTICAST_IF   IPV6_MULTICAST_IF
#define IPV6_MULTICAST_LOOP IPV6_MULTICAST_LOOP
#define IPV6_UNICAST_HOPS   IPV6_UNICAST_HOPS
#define IPV6_RECVTCLASS     IPV6_RECVTCLASS
#define IPV6_TCLASS         IPV6_TCLASS
#define IPV6_DONTFRAG       IPV6_DONTFRAG
#define IPV6_HOPLIMIT       IPV6_HOPLIMIT
#define IPV6_HOPOPTS        IPV6_HOPOPTS
#define IPV6_PKTINFO        IPV6_PKTINFO
#define IPV6_RECVRTHDR      IPV6_RECVRTHDR
#define IPV6_RTHDR          IPV6_RTHDR

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_IPV6_H_ */
