#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_IPV6_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_IPV6_H_
#include "libc/runtime/symbolic.h"

#define IPV6_2292DSTOPTS SYMBOLIC(IPV6_2292DSTOPTS)
#define IPV6_2292HOPLIMIT SYMBOLIC(IPV6_2292HOPLIMIT)
#define IPV6_2292HOPOPTS SYMBOLIC(IPV6_2292HOPOPTS)
#define IPV6_2292PKTINFO SYMBOLIC(IPV6_2292PKTINFO)
#define IPV6_2292PKTOPTIONS SYMBOLIC(IPV6_2292PKTOPTIONS)
#define IPV6_2292RTHDR SYMBOLIC(IPV6_2292RTHDR)
#define IPV6_ADDRFORM SYMBOLIC(IPV6_ADDRFORM)
#define IPV6_ADD_MEMBERSHIP SYMBOLIC(IPV6_ADD_MEMBERSHIP)
#define IPV6_AUTHHDR SYMBOLIC(IPV6_AUTHHDR)
#define IPV6_AUTOFLOWLABEL SYMBOLIC(IPV6_AUTOFLOWLABEL)
#define IPV6_CHECKSUM SYMBOLIC(IPV6_CHECKSUM)
#define IPV6_DONTFRAG SYMBOLIC(IPV6_DONTFRAG)
#define IPV6_DROP_MEMBERSHIP SYMBOLIC(IPV6_DROP_MEMBERSHIP)
#define IPV6_DSTOPTS SYMBOLIC(IPV6_DSTOPTS)
#define IPV6_HDRINCL SYMBOLIC(IPV6_HDRINCL)
#define IPV6_HOPLIMIT SYMBOLIC(IPV6_HOPLIMIT)
#define IPV6_HOPOPTS SYMBOLIC(IPV6_HOPOPTS)
#define IPV6_IPSEC_POLICY SYMBOLIC(IPV6_IPSEC_POLICY)
#define IPV6_JOIN_ANYCAST SYMBOLIC(IPV6_JOIN_ANYCAST)
#define IPV6_JOIN_GROUP SYMBOLIC(IPV6_JOIN_GROUP)
#define IPV6_LEAVE_ANYCAST SYMBOLIC(IPV6_LEAVE_ANYCAST)
#define IPV6_LEAVE_GROUP SYMBOLIC(IPV6_LEAVE_GROUP)
#define IPV6_MINHOPCOUNT SYMBOLIC(IPV6_MINHOPCOUNT)
#define IPV6_MTU SYMBOLIC(IPV6_MTU)
#define IPV6_MTU_DISCOVER SYMBOLIC(IPV6_MTU_DISCOVER)
#define IPV6_MULTICAST_HOPS SYMBOLIC(IPV6_MULTICAST_HOPS)
#define IPV6_MULTICAST_IF SYMBOLIC(IPV6_MULTICAST_IF)
#define IPV6_MULTICAST_LOOP SYMBOLIC(IPV6_MULTICAST_LOOP)
#define IPV6_NEXTHOP SYMBOLIC(IPV6_NEXTHOP)
#define IPV6_ORIGDSTADDR SYMBOLIC(IPV6_ORIGDSTADDR)
#define IPV6_PATHMTU SYMBOLIC(IPV6_PATHMTU)
#define IPV6_PKTINFO SYMBOLIC(IPV6_PKTINFO)
#define IPV6_PMTUDISC_DO SYMBOLIC(IPV6_PMTUDISC_DO)
#define IPV6_PMTUDISC_DONT SYMBOLIC(IPV6_PMTUDISC_DONT)
#define IPV6_PMTUDISC_INTERFACE SYMBOLIC(IPV6_PMTUDISC_INTERFACE)
#define IPV6_PMTUDISC_OMIT SYMBOLIC(IPV6_PMTUDISC_OMIT)
#define IPV6_PMTUDISC_PROBE SYMBOLIC(IPV6_PMTUDISC_PROBE)
#define IPV6_PMTUDISC_WANT SYMBOLIC(IPV6_PMTUDISC_WANT)
#define IPV6_RECVDSTOPTS SYMBOLIC(IPV6_RECVDSTOPTS)
#define IPV6_RECVERR SYMBOLIC(IPV6_RECVERR)
#define IPV6_RECVHOPLIMIT SYMBOLIC(IPV6_RECVHOPLIMIT)
#define IPV6_RECVHOPOPTS SYMBOLIC(IPV6_RECVHOPOPTS)
#define IPV6_RECVORIGDSTADDR SYMBOLIC(IPV6_RECVORIGDSTADDR)
#define IPV6_RECVPATHMTU SYMBOLIC(IPV6_RECVPATHMTU)
#define IPV6_RECVPKTINFO SYMBOLIC(IPV6_RECVPKTINFO)
#define IPV6_RECVRTHDR SYMBOLIC(IPV6_RECVRTHDR)
#define IPV6_RECVTCLASS SYMBOLIC(IPV6_RECVTCLASS)
#define IPV6_ROUTER_ALERT SYMBOLIC(IPV6_ROUTER_ALERT)
#define IPV6_RTHDR SYMBOLIC(IPV6_RTHDR)
#define IPV6_RTHDRDSTOPTS SYMBOLIC(IPV6_RTHDRDSTOPTS)
#define IPV6_RTHDR_LOOSE SYMBOLIC(IPV6_RTHDR_LOOSE)
#define IPV6_RTHDR_STRICT SYMBOLIC(IPV6_RTHDR_STRICT)
#define IPV6_RTHDR_TYPE_0 SYMBOLIC(IPV6_RTHDR_TYPE_0)
#define IPV6_RXDSTOPTS SYMBOLIC(IPV6_RXDSTOPTS)
#define IPV6_RXHOPOPTS SYMBOLIC(IPV6_RXHOPOPTS)
#define IPV6_TCLASS SYMBOLIC(IPV6_TCLASS)
#define IPV6_UNICAST_HOPS SYMBOLIC(IPV6_UNICAST_HOPS)
#define IPV6_V6ONLY SYMBOLIC(IPV6_V6ONLY)
#define IPV6_XFRM_POLICY SYMBOLIC(IPV6_XFRM_POLICY)

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const long IPV6_2292DSTOPTS;
extern const long IPV6_2292HOPLIMIT;
extern const long IPV6_2292HOPOPTS;
extern const long IPV6_2292PKTINFO;
extern const long IPV6_2292PKTOPTIONS;
extern const long IPV6_2292RTHDR;
extern const long IPV6_ADDRFORM;
extern const long IPV6_ADD_MEMBERSHIP;
extern const long IPV6_AUTHHDR;
extern const long IPV6_AUTOFLOWLABEL;
extern const long IPV6_CHECKSUM;
extern const long IPV6_DONTFRAG;
extern const long IPV6_DROP_MEMBERSHIP;
extern const long IPV6_DSTOPTS;
extern const long IPV6_HDRINCL;
extern const long IPV6_HOPLIMIT;
extern const long IPV6_HOPOPTS;
extern const long IPV6_IPSEC_POLICY;
extern const long IPV6_JOIN_ANYCAST;
extern const long IPV6_JOIN_GROUP;
extern const long IPV6_LEAVE_ANYCAST;
extern const long IPV6_LEAVE_GROUP;
extern const long IPV6_MINHOPCOUNT;
extern const long IPV6_MTU;
extern const long IPV6_MTU_DISCOVER;
extern const long IPV6_MULTICAST_HOPS;
extern const long IPV6_MULTICAST_IF;
extern const long IPV6_MULTICAST_LOOP;
extern const long IPV6_NEXTHOP;
extern const long IPV6_ORIGDSTADDR;
extern const long IPV6_PATHMTU;
extern const long IPV6_PKTINFO;
extern const long IPV6_PMTUDISC_DO;
extern const long IPV6_PMTUDISC_DONT;
extern const long IPV6_PMTUDISC_INTERFACE;
extern const long IPV6_PMTUDISC_OMIT;
extern const long IPV6_PMTUDISC_PROBE;
extern const long IPV6_PMTUDISC_WANT;
extern const long IPV6_RECVDSTOPTS;
extern const long IPV6_RECVERR;
extern const long IPV6_RECVHOPLIMIT;
extern const long IPV6_RECVHOPOPTS;
extern const long IPV6_RECVORIGDSTADDR;
extern const long IPV6_RECVPATHMTU;
extern const long IPV6_RECVPKTINFO;
extern const long IPV6_RECVRTHDR;
extern const long IPV6_RECVTCLASS;
extern const long IPV6_ROUTER_ALERT;
extern const long IPV6_RTHDR;
extern const long IPV6_RTHDRDSTOPTS;
extern const long IPV6_RTHDR_LOOSE;
extern const long IPV6_RTHDR_STRICT;
extern const long IPV6_RTHDR_TYPE_0;
extern const long IPV6_RXDSTOPTS;
extern const long IPV6_RXHOPOPTS;
extern const long IPV6_TCLASS;
extern const long IPV6_UNICAST_HOPS;
extern const long IPV6_V6ONLY;
extern const long IPV6_XFRM_POLICY;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_IPV6_H_ */
