#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_IPV6_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_IPV6_H_
COSMOPOLITAN_C_START_

extern const int IPV6_2292DSTOPTS;
extern const int IPV6_2292HOPLIMIT;
extern const int IPV6_2292HOPOPTS;
extern const int IPV6_2292PKTINFO;
extern const int IPV6_2292PKTOPTIONS;
extern const int IPV6_2292RTHDR;
extern const int IPV6_ADDRFORM;
extern const int IPV6_ADD_MEMBERSHIP;
extern const int IPV6_AUTHHDR;
extern const int IPV6_AUTOFLOWLABEL;
extern const int IPV6_CHECKSUM;
extern const int IPV6_DONTFRAG;
extern const int IPV6_DROP_MEMBERSHIP;
extern const int IPV6_DSTOPTS;
extern const int IPV6_HDRINCL;
extern const int IPV6_HOPLIMIT;
extern const int IPV6_HOPOPTS;
extern const int IPV6_IPSEC_POLICY;
extern const int IPV6_JOIN_ANYCAST;
extern const int IPV6_JOIN_GROUP;
extern const int IPV6_LEAVE_ANYCAST;
extern const int IPV6_LEAVE_GROUP;
extern const int IPV6_MINHOPCOUNT;
extern const int IPV6_MTU;
extern const int IPV6_MTU_DISCOVER;
extern const int IPV6_MULTICAST_HOPS;
extern const int IPV6_MULTICAST_IF;
extern const int IPV6_MULTICAST_LOOP;
extern const int IPV6_NEXTHOP;
extern const int IPV6_ORIGDSTADDR;
extern const int IPV6_PATHMTU;
extern const int IPV6_PKTINFO;
extern const int IPV6_PMTUDISC_DO;
extern const int IPV6_PMTUDISC_DONT;
extern const int IPV6_PMTUDISC_INTERFACE;
extern const int IPV6_PMTUDISC_OMIT;
extern const int IPV6_PMTUDISC_PROBE;
extern const int IPV6_PMTUDISC_WANT;
extern const int IPV6_RECVDSTOPTS;
extern const int IPV6_RECVERR;
extern const int IPV6_RECVHOPLIMIT;
extern const int IPV6_RECVHOPOPTS;
extern const int IPV6_RECVORIGDSTADDR;
extern const int IPV6_RECVPATHMTU;
extern const int IPV6_RECVPKTINFO;
extern const int IPV6_RECVRTHDR;
extern const int IPV6_RECVTCLASS;
extern const int IPV6_ROUTER_ALERT;
extern const int IPV6_RTHDR;
extern const int IPV6_RTHDRDSTOPTS;
extern const int IPV6_RTHDR_LOOSE;
extern const int IPV6_RTHDR_STRICT;
extern const int IPV6_RTHDR_TYPE_0;
extern const int IPV6_RXDSTOPTS;
extern const int IPV6_RXHOPOPTS;
extern const int IPV6_TCLASS;
extern const int IPV6_UNICAST_HOPS;
extern const int IPV6_V6ONLY;
extern const int IPV6_XFRM_POLICY;

#define IPV6_2292DSTOPTS        IPV6_2292DSTOPTS
#define IPV6_2292HOPLIMIT       IPV6_2292HOPLIMIT
#define IPV6_2292HOPOPTS        IPV6_2292HOPOPTS
#define IPV6_2292PKTINFO        IPV6_2292PKTINFO
#define IPV6_2292PKTOPTIONS     IPV6_2292PKTOPTIONS
#define IPV6_2292RTHDR          IPV6_2292RTHDR
#define IPV6_ADDRFORM           IPV6_ADDRFORM
#define IPV6_ADD_MEMBERSHIP     IPV6_ADD_MEMBERSHIP
#define IPV6_AUTHHDR            IPV6_AUTHHDR
#define IPV6_AUTOFLOWLABEL      IPV6_AUTOFLOWLABEL
#define IPV6_CHECKSUM           IPV6_CHECKSUM
#define IPV6_DONTFRAG           IPV6_DONTFRAG
#define IPV6_DROP_MEMBERSHIP    IPV6_DROP_MEMBERSHIP
#define IPV6_DSTOPTS            IPV6_DSTOPTS
#define IPV6_HDRINCL            IPV6_HDRINCL
#define IPV6_HOPLIMIT           IPV6_HOPLIMIT
#define IPV6_HOPOPTS            IPV6_HOPOPTS
#define IPV6_IPSEC_POLICY       IPV6_IPSEC_POLICY
#define IPV6_JOIN_ANYCAST       IPV6_JOIN_ANYCAST
#define IPV6_JOIN_GROUP         IPV6_JOIN_GROUP
#define IPV6_LEAVE_ANYCAST      IPV6_LEAVE_ANYCAST
#define IPV6_LEAVE_GROUP        IPV6_LEAVE_GROUP
#define IPV6_MINHOPCOUNT        IPV6_MINHOPCOUNT
#define IPV6_MTU                IPV6_MTU
#define IPV6_MTU_DISCOVER       IPV6_MTU_DISCOVER
#define IPV6_MULTICAST_HOPS     IPV6_MULTICAST_HOPS
#define IPV6_MULTICAST_IF       IPV6_MULTICAST_IF
#define IPV6_MULTICAST_LOOP     IPV6_MULTICAST_LOOP
#define IPV6_NEXTHOP            IPV6_NEXTHOP
#define IPV6_ORIGDSTADDR        IPV6_ORIGDSTADDR
#define IPV6_PATHMTU            IPV6_PATHMTU
#define IPV6_PKTINFO            IPV6_PKTINFO
#define IPV6_PMTUDISC_DO        IPV6_PMTUDISC_DO
#define IPV6_PMTUDISC_DONT      IPV6_PMTUDISC_DONT
#define IPV6_PMTUDISC_INTERFACE IPV6_PMTUDISC_INTERFACE
#define IPV6_PMTUDISC_OMIT      IPV6_PMTUDISC_OMIT
#define IPV6_PMTUDISC_PROBE     IPV6_PMTUDISC_PROBE
#define IPV6_PMTUDISC_WANT      IPV6_PMTUDISC_WANT
#define IPV6_RECVDSTOPTS        IPV6_RECVDSTOPTS
#define IPV6_RECVERR            IPV6_RECVERR
#define IPV6_RECVHOPLIMIT       IPV6_RECVHOPLIMIT
#define IPV6_RECVHOPOPTS        IPV6_RECVHOPOPTS
#define IPV6_RECVORIGDSTADDR    IPV6_RECVORIGDSTADDR
#define IPV6_RECVPATHMTU        IPV6_RECVPATHMTU
#define IPV6_RECVPKTINFO        IPV6_RECVPKTINFO
#define IPV6_RECVRTHDR          IPV6_RECVRTHDR
#define IPV6_RECVTCLASS         IPV6_RECVTCLASS
#define IPV6_ROUTER_ALERT       IPV6_ROUTER_ALERT
#define IPV6_RTHDR              IPV6_RTHDR
#define IPV6_RTHDRDSTOPTS       IPV6_RTHDRDSTOPTS
#define IPV6_RTHDR_LOOSE        IPV6_RTHDR_LOOSE
#define IPV6_RTHDR_STRICT       IPV6_RTHDR_STRICT
#define IPV6_RTHDR_TYPE_0       IPV6_RTHDR_TYPE_0
#define IPV6_RXDSTOPTS          IPV6_RXDSTOPTS
#define IPV6_RXHOPOPTS          IPV6_RXHOPOPTS
#define IPV6_TCLASS             IPV6_TCLASS
#define IPV6_UNICAST_HOPS       IPV6_UNICAST_HOPS
#define IPV6_V6ONLY             IPV6_V6ONLY
#define IPV6_XFRM_POLICY        IPV6_XFRM_POLICY


COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_IPV6_H_ */
