#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_MCAST_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_MCAST_H_
#include "libc/runtime/symbolic.h"

#define MCAST_BLOCK_SOURCE SYMBOLIC(MCAST_BLOCK_SOURCE)
#define MCAST_EXCLUDE SYMBOLIC(MCAST_EXCLUDE)
#define MCAST_INCLUDE SYMBOLIC(MCAST_INCLUDE)
#define MCAST_JOIN_GROUP SYMBOLIC(MCAST_JOIN_GROUP)
#define MCAST_JOIN_SOURCE_GROUP SYMBOLIC(MCAST_JOIN_SOURCE_GROUP)
#define MCAST_LEAVE_GROUP SYMBOLIC(MCAST_LEAVE_GROUP)
#define MCAST_LEAVE_SOURCE_GROUP SYMBOLIC(MCAST_LEAVE_SOURCE_GROUP)
#define MCAST_MSFILTER SYMBOLIC(MCAST_MSFILTER)
#define MCAST_UNBLOCK_SOURCE SYMBOLIC(MCAST_UNBLOCK_SOURCE)

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const int MCAST_BLOCK_SOURCE;
extern const int MCAST_EXCLUDE;
extern const int MCAST_INCLUDE;
extern const int MCAST_JOIN_GROUP;
extern const int MCAST_JOIN_SOURCE_GROUP;
extern const int MCAST_LEAVE_GROUP;
extern const int MCAST_LEAVE_SOURCE_GROUP;
extern const int MCAST_MSFILTER;
extern const int MCAST_UNBLOCK_SOURCE;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_MCAST_H_ */
