#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_MLOCK_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_MLOCK_H_
COSMOPOLITAN_C_START_

extern const int MCL_CURRENT;
extern const int MCL_FUTURE;
extern const int MCL_ONFAULT;

COSMOPOLITAN_C_END_

#define MCL_CURRENT 1
#define MCL_FUTURE  2
#define MCL_ONFAULT MCL_ONFAULT

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_MLOCK_H_ */
