#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_MREMAP_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_MREMAP_H_

#define MREMAP_MAYMOVE 1
#define MREMAP_FIXED   2

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_MREMAP_H_ */
