#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_POSIX_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_POSIX_H_
#include "libc/runtime/symbolic.h"

#define POSIX_FADV_DONTNEED SYMBOLIC(POSIX_FADV_DONTNEED)
#define POSIX_FADV_NOREUSE SYMBOLIC(POSIX_FADV_NOREUSE)
#define POSIX_FADV_NORMAL SYMBOLIC(POSIX_FADV_NORMAL)
#define POSIX_FADV_RANDOM SYMBOLIC(POSIX_FADV_RANDOM)
#define POSIX_FADV_SEQUENTIAL SYMBOLIC(POSIX_FADV_SEQUENTIAL)
#define POSIX_FADV_WILLNEED SYMBOLIC(POSIX_FADV_WILLNEED)
#define POSIX_MADV_DONTNEED SYMBOLIC(POSIX_MADV_DONTNEED)
#define POSIX_MADV_NORMAL SYMBOLIC(POSIX_MADV_NORMAL)
#define POSIX_MADV_RANDOM SYMBOLIC(POSIX_MADV_RANDOM)
#define POSIX_MADV_SEQUENTIAL SYMBOLIC(POSIX_MADV_SEQUENTIAL)
#define POSIX_MADV_WILLNEED SYMBOLIC(POSIX_MADV_WILLNEED)
#define POSIX_SPAWN_RESETIDS SYMBOLIC(POSIX_SPAWN_RESETIDS)
#define POSIX_SPAWN_SETPGROUP SYMBOLIC(POSIX_SPAWN_SETPGROUP)
#define POSIX_SPAWN_SETSCHEDPARAM SYMBOLIC(POSIX_SPAWN_SETSCHEDPARAM)
#define POSIX_SPAWN_SETSCHEDULER SYMBOLIC(POSIX_SPAWN_SETSCHEDULER)
#define POSIX_SPAWN_SETSIGDEF SYMBOLIC(POSIX_SPAWN_SETSIGDEF)
#define POSIX_SPAWN_SETSIGMASK SYMBOLIC(POSIX_SPAWN_SETSIGMASK)
#define POSIX_SPAWN_USEVFORK SYMBOLIC(POSIX_SPAWN_USEVFORK)

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

hidden extern const long POSIX_FADV_DONTNEED;
hidden extern const long POSIX_FADV_NOREUSE;
hidden extern const long POSIX_FADV_NORMAL;
hidden extern const long POSIX_FADV_RANDOM;
hidden extern const long POSIX_FADV_SEQUENTIAL;
hidden extern const long POSIX_FADV_WILLNEED;
hidden extern const long POSIX_MADV_DONTNEED;
hidden extern const long POSIX_MADV_NORMAL;
hidden extern const long POSIX_MADV_RANDOM;
hidden extern const long POSIX_MADV_SEQUENTIAL;
hidden extern const long POSIX_MADV_WILLNEED;
hidden extern const long POSIX_SPAWN_RESETIDS;
hidden extern const long POSIX_SPAWN_SETPGROUP;
hidden extern const long POSIX_SPAWN_SETSCHEDPARAM;
hidden extern const long POSIX_SPAWN_SETSCHEDULER;
hidden extern const long POSIX_SPAWN_SETSIGDEF;
hidden extern const long POSIX_SPAWN_SETSIGMASK;
hidden extern const long POSIX_SPAWN_USEVFORK;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_POSIX_H_ */
