#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_POSIX_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_POSIX_H_
#include "libc/runtime/symbolic.h"
#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const int POSIX_FADV_DONTNEED;
extern const int POSIX_FADV_NOREUSE;
extern const int POSIX_MADV_DONTNEED;
extern const int POSIX_MADV_DONTNEED;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */

#define POSIX_FADV_NORMAL     LITERALLY(0)
#define POSIX_FADV_RANDOM     LITERALLY(1)
#define POSIX_FADV_SEQUENTIAL LITERALLY(2)
#define POSIX_FADV_WILLNEED   LITERALLY(3)

#define POSIX_FADV_DONTNEED SYMBOLIC(POSIX_FADV_DONTNEED)
#define POSIX_FADV_NOREUSE  SYMBOLIC(POSIX_FADV_NOREUSE)

#define POSIX_MADV_NORMAL     LITERALLY(0)
#define POSIX_MADV_RANDOM     LITERALLY(1)
#define POSIX_MADV_SEQUENTIAL LITERALLY(2)
#define POSIX_MADV_WILLNEED   LITERALLY(3)

#define POSIX_MADV_DONTNEED SYMBOLIC(POSIX_MADV_DONTNEED)

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_POSIX_H_ */
