#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_POSIX_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_POSIX_H_

#define POSIX_FADV_NORMAL     0
#define POSIX_FADV_RANDOM     1
#define POSIX_FADV_SEQUENTIAL 2
#define POSIX_FADV_WILLNEED   3
#define POSIX_FADV_DONTNEED   4
#define POSIX_FADV_NOREUSE    5

#define POSIX_MADV_NORMAL     0
#define POSIX_MADV_RANDOM     1
#define POSIX_MADV_SEQUENTIAL 2
#define POSIX_MADV_WILLNEED   3
#define POSIX_MADV_DONTNEED   4

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_POSIX_H_ */
