#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_READ_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_READ_H_

#define READ_10 READ_10
#define READ_12 READ_12
#define READ_6 READ_6
#define READ_BLOCK_LIMITS READ_BLOCK_LIMITS
#define READ_BUFFER READ_BUFFER
#define READ_CAPACITY READ_CAPACITY
#define READ_DEFECT_DATA READ_DEFECT_DATA
#define READ_ELEMENT_STATUS READ_ELEMENT_STATUS
#define READ_LONG READ_LONG
#define READ_POSITION READ_POSITION
#define READ_REVERSE READ_REVERSE
#define READ_TOC READ_TOC

COSMOPOLITAN_C_START_

extern const long READ_10;
extern const long READ_12;
extern const long READ_6;
extern const long READ_BLOCK_LIMITS;
extern const long READ_BUFFER;
extern const long READ_CAPACITY;
extern const long READ_DEFECT_DATA;
extern const long READ_ELEMENT_STATUS;
extern const long READ_LONG;
extern const long READ_POSITION;
extern const long READ_REVERSE;
extern const long READ_TOC;

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_READ_H_ */
