#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_RLIM_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_RLIM_H_
COSMOPOLITAN_C_START_

extern const uint64_t RLIM_INFINITY;
extern const uint64_t RLIM_NLIMITS;
extern const uint64_t RLIM_SAVED_CUR;
extern const uint64_t RLIM_SAVED_MAX;

#define RLIM_INFINITY  RLIM_INFINITY
#define RLIM_NLIMITS   RLIM_NLIMITS
#define RLIM_SAVED_CUR RLIM_SAVED_CUR
#define RLIM_SAVED_MAX RLIM_SAVED_MAX


COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_RLIM_H_ */
