#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_SCM_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_SCM_H_
#include "libc/runtime/symbolic.h"
#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const int SCM_TIMESTAMP;
extern const int SCM_CREDENTIALS;
extern const int SCM_TIMESTAMPING;
extern const int SCM_TIMESTAMPNS;
extern const int SCM_WIFI_STATUS;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */

#define SCM_RIGHTS       LITERALLY(1)
#define SCM_TIMESTAMP    SYMBOLIC(SCM_TIMESTAMP)
#define SCM_CREDENTIALS  SYMBOLIC(SCM_CREDENTIALS)
#define SCM_TIMESTAMPING SYMBOLIC(SCM_TIMESTAMPING)
#define SCM_TIMESTAMPNS  SYMBOLIC(SCM_TIMESTAMPNS)
#define SCM_WIFI_STATUS  SYMBOLIC(SCM_WIFI_STATUS)

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_SCM_H_ */
