#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_SCSI_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_SCSI_H_
#include "libc/runtime/symbolic.h"

#define SCSI_IOCTL_BENCHMARK_COMMAND SYMBOLIC(SCSI_IOCTL_BENCHMARK_COMMAND)
#define SCSI_IOCTL_DOORLOCK SYMBOLIC(SCSI_IOCTL_DOORLOCK)
#define SCSI_IOCTL_DOORUNLOCK SYMBOLIC(SCSI_IOCTL_DOORUNLOCK)
#define SCSI_IOCTL_GET_BUS_NUMBER SYMBOLIC(SCSI_IOCTL_GET_BUS_NUMBER)
#define SCSI_IOCTL_GET_IDLUN SYMBOLIC(SCSI_IOCTL_GET_IDLUN)
#define SCSI_IOCTL_PROBE_HOST SYMBOLIC(SCSI_IOCTL_PROBE_HOST)
#define SCSI_IOCTL_SEND_COMMAND SYMBOLIC(SCSI_IOCTL_SEND_COMMAND)
#define SCSI_IOCTL_START_UNIT SYMBOLIC(SCSI_IOCTL_START_UNIT)
#define SCSI_IOCTL_STOP_UNIT SYMBOLIC(SCSI_IOCTL_STOP_UNIT)
#define SCSI_IOCTL_SYNC SYMBOLIC(SCSI_IOCTL_SYNC)
#define SCSI_IOCTL_TAGGED_DISABLE SYMBOLIC(SCSI_IOCTL_TAGGED_DISABLE)
#define SCSI_IOCTL_TAGGED_ENABLE SYMBOLIC(SCSI_IOCTL_TAGGED_ENABLE)
#define SCSI_IOCTL_TEST_UNIT_READY SYMBOLIC(SCSI_IOCTL_TEST_UNIT_READY)

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

hidden extern const long SCSI_IOCTL_BENCHMARK_COMMAND;
hidden extern const long SCSI_IOCTL_DOORLOCK;
hidden extern const long SCSI_IOCTL_DOORUNLOCK;
hidden extern const long SCSI_IOCTL_GET_BUS_NUMBER;
hidden extern const long SCSI_IOCTL_GET_IDLUN;
hidden extern const long SCSI_IOCTL_PROBE_HOST;
hidden extern const long SCSI_IOCTL_SEND_COMMAND;
hidden extern const long SCSI_IOCTL_START_UNIT;
hidden extern const long SCSI_IOCTL_STOP_UNIT;
hidden extern const long SCSI_IOCTL_SYNC;
hidden extern const long SCSI_IOCTL_TAGGED_DISABLE;
hidden extern const long SCSI_IOCTL_TAGGED_ENABLE;
hidden extern const long SCSI_IOCTL_TEST_UNIT_READY;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_SCSI_H_ */
