#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_SECCOMP_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_SECCOMP_H_

#define SECCOMP_SET_MODE_STRICT          0
#define SECCOMP_SET_MODE_FILTER          1
#define SECCOMP_GET_ACTION_AVAIL         2
#define SECCOMP_GET_NOTIF_SIZES          3
#define SECCOMP_FILTER_FLAG_TSYNC        (1UL << 0)
#define SECCOMP_FILTER_FLAG_LOG          (1UL << 1)
#define SECCOMP_FILTER_FLAG_SPEC_ALLOW   (1UL << 2)
#define SECCOMP_FILTER_FLAG_NEW_LISTENER (1UL << 3)
#define SECCOMP_FILTER_FLAG_TSYNC_ESRCH  (1UL << 4)
#define SECCOMP_RET_KILL_PROCESS         0x80000000U
#define SECCOMP_RET_KILL_THREAD          0x00000000U
#define SECCOMP_RET_KILL                 SECCOMP_RET_KILL_THREAD
#define SECCOMP_RET_TRAP                 0x00030000U
#define SECCOMP_RET_ERRNO                0x00050000U
#define SECCOMP_RET_USER_NOTIF           0x7fc00000U
#define SECCOMP_RET_TRACE                0x7ff00000U
#define SECCOMP_RET_LOG                  0x7ffc0000U
#define SECCOMP_RET_ALLOW                0x7fff0000U
#define SECCOMP_RET_ACTION_FULL          0xffff0000U
#define SECCOMP_RET_ACTION               0x7fff0000U
#define SECCOMP_RET_DATA                 0x0000ffffU
#define SECCOMP_USER_NOTIF_FLAG_CONTINUE (1UL << 0)
#define SECCOMP_ADDFD_FLAG_SETFD         (1UL << 0)
#define SECCOMP_ADDFD_FLAG_SEND          (1UL << 1)

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_SECCOMP_H_ */
