#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_SIO_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_SIO_H_
#include "libc/runtime/symbolic.h"

#define SIOCADDDLCI SYMBOLIC(SIOCADDDLCI)
#define SIOCADDMULTI SYMBOLIC(SIOCADDMULTI)
#define SIOCADDRT SYMBOLIC(SIOCADDRT)
#define SIOCATMARK SYMBOLIC(SIOCATMARK)
#define SIOCDARP SYMBOLIC(SIOCDARP)
#define SIOCDELDLCI SYMBOLIC(SIOCDELDLCI)
#define SIOCDELMULTI SYMBOLIC(SIOCDELMULTI)
#define SIOCDELRT SYMBOLIC(SIOCDELRT)
#define SIOCDEVPRIVATE SYMBOLIC(SIOCDEVPRIVATE)
#define SIOCDIFADDR SYMBOLIC(SIOCDIFADDR)
#define SIOCDRARP SYMBOLIC(SIOCDRARP)
#define SIOCGARP SYMBOLIC(SIOCGARP)
#define SIOCGIFADDR SYMBOLIC(SIOCGIFADDR)
#define SIOCGIFBR SYMBOLIC(SIOCGIFBR)
#define SIOCGIFBRDADDR SYMBOLIC(SIOCGIFBRDADDR)
#define SIOCGIFCONF SYMBOLIC(SIOCGIFCONF)
#define SIOCGIFCOUNT SYMBOLIC(SIOCGIFCOUNT)
#define SIOCGIFDSTADDR SYMBOLIC(SIOCGIFDSTADDR)
#define SIOCGIFENCAP SYMBOLIC(SIOCGIFENCAP)
#define SIOCGIFFLAGS SYMBOLIC(SIOCGIFFLAGS)
#define SIOCGIFHWADDR SYMBOLIC(SIOCGIFHWADDR)
#define SIOCGIFINDEX SYMBOLIC(SIOCGIFINDEX)
#define SIOCGIFMAP SYMBOLIC(SIOCGIFMAP)
#define SIOCGIFMEM SYMBOLIC(SIOCGIFMEM)
#define SIOCGIFMETRIC SYMBOLIC(SIOCGIFMETRIC)
#define SIOCGIFMTU SYMBOLIC(SIOCGIFMTU)
#define SIOCGIFNAME SYMBOLIC(SIOCGIFNAME)
#define SIOCGIFNETMASK SYMBOLIC(SIOCGIFNETMASK)
#define SIOCGIFPFLAGS SYMBOLIC(SIOCGIFPFLAGS)
#define SIOCGIFSLAVE SYMBOLIC(SIOCGIFSLAVE)
#define SIOCGIFTXQLEN SYMBOLIC(SIOCGIFTXQLEN)
#define SIOCGPGRP SYMBOLIC(SIOCGPGRP)
#define SIOCGRARP SYMBOLIC(SIOCGRARP)
#define SIOCGSTAMP SYMBOLIC(SIOCGSTAMP)
#define SIOCGSTAMPNS SYMBOLIC(SIOCGSTAMPNS)
#define SIOCPROTOPRIVATE SYMBOLIC(SIOCPROTOPRIVATE)
#define SIOCRTMSG SYMBOLIC(SIOCRTMSG)
#define SIOCSARP SYMBOLIC(SIOCSARP)
#define SIOCSIFADDR SYMBOLIC(SIOCSIFADDR)
#define SIOCSIFBR SYMBOLIC(SIOCSIFBR)
#define SIOCSIFBRDADDR SYMBOLIC(SIOCSIFBRDADDR)
#define SIOCSIFDSTADDR SYMBOLIC(SIOCSIFDSTADDR)
#define SIOCSIFENCAP SYMBOLIC(SIOCSIFENCAP)
#define SIOCSIFFLAGS SYMBOLIC(SIOCSIFFLAGS)
#define SIOCSIFHWADDR SYMBOLIC(SIOCSIFHWADDR)
#define SIOCSIFHWBROADCAST SYMBOLIC(SIOCSIFHWBROADCAST)
#define SIOCSIFLINK SYMBOLIC(SIOCSIFLINK)
#define SIOCSIFMAP SYMBOLIC(SIOCSIFMAP)
#define SIOCSIFMEM SYMBOLIC(SIOCSIFMEM)
#define SIOCSIFMETRIC SYMBOLIC(SIOCSIFMETRIC)
#define SIOCSIFMTU SYMBOLIC(SIOCSIFMTU)
#define SIOCSIFNAME SYMBOLIC(SIOCSIFNAME)
#define SIOCSIFNETMASK SYMBOLIC(SIOCSIFNETMASK)
#define SIOCSIFPFLAGS SYMBOLIC(SIOCSIFPFLAGS)
#define SIOCSIFSLAVE SYMBOLIC(SIOCSIFSLAVE)
#define SIOCSIFTXQLEN SYMBOLIC(SIOCSIFTXQLEN)
#define SIOCSPGRP SYMBOLIC(SIOCSPGRP)
#define SIOCSRARP SYMBOLIC(SIOCSRARP)
#define SIOGIFINDEX SYMBOLIC(SIOGIFINDEX)

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const long SIOCADDDLCI;
extern const long SIOCADDMULTI;
extern const long SIOCADDRT;
extern const long SIOCATMARK;
extern const long SIOCDARP;
extern const long SIOCDELDLCI;
extern const long SIOCDELMULTI;
extern const long SIOCDELRT;
extern const long SIOCDEVPRIVATE;
extern const long SIOCDIFADDR;
extern const long SIOCDRARP;
extern const long SIOCGARP;
extern const long SIOCGIFADDR;
extern const long SIOCGIFBR;
extern const long SIOCGIFBRDADDR;
extern const long SIOCGIFCONF;
extern const long SIOCGIFCOUNT;
extern const long SIOCGIFDSTADDR;
extern const long SIOCGIFENCAP;
extern const long SIOCGIFFLAGS;
extern const long SIOCGIFHWADDR;
extern const long SIOCGIFINDEX;
extern const long SIOCGIFMAP;
extern const long SIOCGIFMEM;
extern const long SIOCGIFMETRIC;
extern const long SIOCGIFMTU;
extern const long SIOCGIFNAME;
extern const long SIOCGIFNETMASK;
extern const long SIOCGIFPFLAGS;
extern const long SIOCGIFSLAVE;
extern const long SIOCGIFTXQLEN;
extern const long SIOCGPGRP;
extern const long SIOCGRARP;
extern const long SIOCGSTAMP;
extern const long SIOCGSTAMPNS;
extern const long SIOCPROTOPRIVATE;
extern const long SIOCRTMSG;
extern const long SIOCSARP;
extern const long SIOCSIFADDR;
extern const long SIOCSIFBR;
extern const long SIOCSIFBRDADDR;
extern const long SIOCSIFDSTADDR;
extern const long SIOCSIFENCAP;
extern const long SIOCSIFFLAGS;
extern const long SIOCSIFHWADDR;
extern const long SIOCSIFHWBROADCAST;
extern const long SIOCSIFLINK;
extern const long SIOCSIFMAP;
extern const long SIOCSIFMEM;
extern const long SIOCSIFMETRIC;
extern const long SIOCSIFMTU;
extern const long SIOCSIFNAME;
extern const long SIOCSIFNETMASK;
extern const long SIOCSIFPFLAGS;
extern const long SIOCSIFSLAVE;
extern const long SIOCSIFTXQLEN;
extern const long SIOCSPGRP;
extern const long SIOCSRARP;
extern const long SIOGIFINDEX;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_SIO_H_ */
