#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_SIO_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_SIO_H_
#include "libc/runtime/symbolic.h"

#define SIOCADDDLCI SYMBOLIC(SIOCADDDLCI)
#define SIOCADDMULTI SYMBOLIC(SIOCADDMULTI)
#define SIOCADDRT SYMBOLIC(SIOCADDRT)
#define SIOCATMARK SYMBOLIC(SIOCATMARK)
#define SIOCDARP SYMBOLIC(SIOCDARP)
#define SIOCDELDLCI SYMBOLIC(SIOCDELDLCI)
#define SIOCDELMULTI SYMBOLIC(SIOCDELMULTI)
#define SIOCDELRT SYMBOLIC(SIOCDELRT)
#define SIOCDEVPRIVATE SYMBOLIC(SIOCDEVPRIVATE)
#define SIOCDIFADDR SYMBOLIC(SIOCDIFADDR)
#define SIOCDRARP SYMBOLIC(SIOCDRARP)
#define SIOCGARP SYMBOLIC(SIOCGARP)
#define SIOCGIFADDR SYMBOLIC(SIOCGIFADDR)
#define SIOCGIFBR SYMBOLIC(SIOCGIFBR)
#define SIOCGIFBRDADDR SYMBOLIC(SIOCGIFBRDADDR)
#define SIOCGIFCONF SYMBOLIC(SIOCGIFCONF)
#define SIOCGIFCOUNT SYMBOLIC(SIOCGIFCOUNT)
#define SIOCGIFDSTADDR SYMBOLIC(SIOCGIFDSTADDR)
#define SIOCGIFENCAP SYMBOLIC(SIOCGIFENCAP)
#define SIOCGIFFLAGS SYMBOLIC(SIOCGIFFLAGS)
#define SIOCGIFHWADDR SYMBOLIC(SIOCGIFHWADDR)
#define SIOCGIFINDEX SYMBOLIC(SIOCGIFINDEX)
#define SIOCGIFMAP SYMBOLIC(SIOCGIFMAP)
#define SIOCGIFMEM SYMBOLIC(SIOCGIFMEM)
#define SIOCGIFMETRIC SYMBOLIC(SIOCGIFMETRIC)
#define SIOCGIFMTU SYMBOLIC(SIOCGIFMTU)
#define SIOCGIFNAME SYMBOLIC(SIOCGIFNAME)
#define SIOCGIFNETMASK SYMBOLIC(SIOCGIFNETMASK)
#define SIOCGIFPFLAGS SYMBOLIC(SIOCGIFPFLAGS)
#define SIOCGIFSLAVE SYMBOLIC(SIOCGIFSLAVE)
#define SIOCGIFTXQLEN SYMBOLIC(SIOCGIFTXQLEN)
#define SIOCGPGRP SYMBOLIC(SIOCGPGRP)
#define SIOCGRARP SYMBOLIC(SIOCGRARP)
#define SIOCGSTAMP SYMBOLIC(SIOCGSTAMP)
#define SIOCGSTAMPNS SYMBOLIC(SIOCGSTAMPNS)
#define SIOCPROTOPRIVATE SYMBOLIC(SIOCPROTOPRIVATE)
#define SIOCRTMSG SYMBOLIC(SIOCRTMSG)
#define SIOCSARP SYMBOLIC(SIOCSARP)
#define SIOCSIFADDR SYMBOLIC(SIOCSIFADDR)
#define SIOCSIFBR SYMBOLIC(SIOCSIFBR)
#define SIOCSIFBRDADDR SYMBOLIC(SIOCSIFBRDADDR)
#define SIOCSIFDSTADDR SYMBOLIC(SIOCSIFDSTADDR)
#define SIOCSIFENCAP SYMBOLIC(SIOCSIFENCAP)
#define SIOCSIFFLAGS SYMBOLIC(SIOCSIFFLAGS)
#define SIOCSIFHWADDR SYMBOLIC(SIOCSIFHWADDR)
#define SIOCSIFHWBROADCAST SYMBOLIC(SIOCSIFHWBROADCAST)
#define SIOCSIFLINK SYMBOLIC(SIOCSIFLINK)
#define SIOCSIFMAP SYMBOLIC(SIOCSIFMAP)
#define SIOCSIFMEM SYMBOLIC(SIOCSIFMEM)
#define SIOCSIFMETRIC SYMBOLIC(SIOCSIFMETRIC)
#define SIOCSIFMTU SYMBOLIC(SIOCSIFMTU)
#define SIOCSIFNAME SYMBOLIC(SIOCSIFNAME)
#define SIOCSIFNETMASK SYMBOLIC(SIOCSIFNETMASK)
#define SIOCSIFPFLAGS SYMBOLIC(SIOCSIFPFLAGS)
#define SIOCSIFSLAVE SYMBOLIC(SIOCSIFSLAVE)
#define SIOCSIFTXQLEN SYMBOLIC(SIOCSIFTXQLEN)
#define SIOCSPGRP SYMBOLIC(SIOCSPGRP)
#define SIOCSRARP SYMBOLIC(SIOCSRARP)
#define SIOGIFINDEX SYMBOLIC(SIOGIFINDEX)

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const uint64_t SIOCADDDLCI;
extern const uint64_t SIOCADDMULTI;
extern const uint64_t SIOCADDRT;
extern const uint64_t SIOCATMARK;
extern const uint64_t SIOCDARP;
extern const uint64_t SIOCDELDLCI;
extern const uint64_t SIOCDELMULTI;
extern const uint64_t SIOCDELRT;
extern const uint64_t SIOCDEVPRIVATE;
extern const uint64_t SIOCDIFADDR;
extern const uint64_t SIOCDRARP;
extern const uint64_t SIOCGARP;
extern const uint64_t SIOCGIFADDR;
extern const uint64_t SIOCGIFBR;
extern const uint64_t SIOCGIFBRDADDR;
extern const uint64_t SIOCGIFCONF;
extern const uint64_t SIOCGIFCOUNT;
extern const uint64_t SIOCGIFDSTADDR;
extern const uint64_t SIOCGIFENCAP;
extern const uint64_t SIOCGIFFLAGS;
extern const uint64_t SIOCGIFHWADDR;
extern const uint64_t SIOCGIFINDEX;
extern const uint64_t SIOCGIFMAP;
extern const uint64_t SIOCGIFMEM;
extern const uint64_t SIOCGIFMETRIC;
extern const uint64_t SIOCGIFMTU;
extern const uint64_t SIOCGIFNAME;
extern const uint64_t SIOCGIFNETMASK;
extern const uint64_t SIOCGIFPFLAGS;
extern const uint64_t SIOCGIFSLAVE;
extern const uint64_t SIOCGIFTXQLEN;
extern const uint64_t SIOCGPGRP;
extern const uint64_t SIOCGRARP;
extern const uint64_t SIOCGSTAMP;
extern const uint64_t SIOCGSTAMPNS;
extern const uint64_t SIOCPROTOPRIVATE;
extern const uint64_t SIOCRTMSG;
extern const uint64_t SIOCSARP;
extern const uint64_t SIOCSIFADDR;
extern const uint64_t SIOCSIFBR;
extern const uint64_t SIOCSIFBRDADDR;
extern const uint64_t SIOCSIFDSTADDR;
extern const uint64_t SIOCSIFENCAP;
extern const uint64_t SIOCSIFFLAGS;
extern const uint64_t SIOCSIFHWADDR;
extern const uint64_t SIOCSIFHWBROADCAST;
extern const uint64_t SIOCSIFLINK;
extern const uint64_t SIOCSIFMAP;
extern const uint64_t SIOCSIFMEM;
extern const uint64_t SIOCSIFMETRIC;
extern const uint64_t SIOCSIFMTU;
extern const uint64_t SIOCSIFNAME;
extern const uint64_t SIOCSIFNETMASK;
extern const uint64_t SIOCSIFPFLAGS;
extern const uint64_t SIOCSIFSLAVE;
extern const uint64_t SIOCSIFTXQLEN;
extern const uint64_t SIOCSPGRP;
extern const uint64_t SIOCSRARP;
extern const uint64_t SIOGIFINDEX;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_SIO_H_ */
