#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_SO_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_SO_H_
#include "libc/runtime/symbolic.h"

#define SO_ACCEPTCONN SYMBOLIC(SO_ACCEPTCONN)
#define SO_ATTACH_BPF SYMBOLIC(SO_ATTACH_BPF)
#define SO_ATTACH_FILTER SYMBOLIC(SO_ATTACH_FILTER)
#define SO_ATTACH_REUSEPORT_CBPF SYMBOLIC(SO_ATTACH_REUSEPORT_CBPF)
#define SO_ATTACH_REUSEPORT_EBPF SYMBOLIC(SO_ATTACH_REUSEPORT_EBPF)
#define SO_BINDTODEVICE SYMBOLIC(SO_BINDTODEVICE)
#define SO_BPF_EXTENSIONS SYMBOLIC(SO_BPF_EXTENSIONS)
#define SO_BROADCAST SYMBOLIC(SO_BROADCAST)
#define SO_BSDCOMPAT SYMBOLIC(SO_BSDCOMPAT)
#define SO_BUSY_POLL SYMBOLIC(SO_BUSY_POLL)
#define SO_CNX_ADVICE SYMBOLIC(SO_CNX_ADVICE)
#define SO_DEBUG SYMBOLIC(SO_DEBUG)
#define SO_DETACH_BPF SYMBOLIC(SO_DETACH_BPF)
#define SO_DETACH_FILTER SYMBOLIC(SO_DETACH_FILTER)
#define SO_DOMAIN SYMBOLIC(SO_DOMAIN)
#define SO_DONTROUTE SYMBOLIC(SO_DONTROUTE)
#define SO_ERROR SYMBOLIC(SO_ERROR)
#define SO_EXCLUSIVEADDRUSE SYMBOLIC(SO_EXCLUSIVEADDRUSE)
#define SO_GET_FILTER SYMBOLIC(SO_GET_FILTER)
#define SO_INCOMING_CPU SYMBOLIC(SO_INCOMING_CPU)
#define SO_KEEPALIVE SYMBOLIC(SO_KEEPALIVE)
#define SO_LINGER SYMBOLIC(SO_LINGER)
#define SO_LOCK_FILTER SYMBOLIC(SO_LOCK_FILTER)
#define SO_MARK SYMBOLIC(SO_MARK)
#define SO_MAX_PACING_RATE SYMBOLIC(SO_MAX_PACING_RATE)
#define SO_NOFCS SYMBOLIC(SO_NOFCS)
#define SO_NO_CHECK SYMBOLIC(SO_NO_CHECK)
#define SO_OOBINLINE SYMBOLIC(SO_OOBINLINE)
#define SO_PASSCRED SYMBOLIC(SO_PASSCRED)
#define SO_PASSSEC SYMBOLIC(SO_PASSSEC)
#define SO_PEEK_OFF SYMBOLIC(SO_PEEK_OFF)
#define SO_PEERCRED SYMBOLIC(SO_PEERCRED)
#define SO_PEERNAME SYMBOLIC(SO_PEERNAME)
#define SO_PEERSEC SYMBOLIC(SO_PEERSEC)
#define SO_PRIORITY SYMBOLIC(SO_PRIORITY)
#define SO_PROTOCOL SYMBOLIC(SO_PROTOCOL)
#define SO_RCVBUF SYMBOLIC(SO_RCVBUF)
#define SO_RCVBUFFORCE SYMBOLIC(SO_RCVBUFFORCE)
#define SO_RCVLOWAT SYMBOLIC(SO_RCVLOWAT)
#define SO_RCVTIMEO SYMBOLIC(SO_RCVTIMEO)
#define SO_REUSEADDR SYMBOLIC(SO_REUSEADDR)
#define SO_REUSEPORT SYMBOLIC(SO_REUSEPORT)
#define SO_RXQ_OVFL SYMBOLIC(SO_RXQ_OVFL)
#define SO_SECURITY_AUTHENTICATION SYMBOLIC(SO_SECURITY_AUTHENTICATION)
#define SO_SECURITY_ENCRYPTION_NETWORK SYMBOLIC(SO_SECURITY_ENCRYPTION_NETWORK)
#define SO_SECURITY_ENCRYPTION_TRANSPORT SYMBOLIC(SO_SECURITY_ENCRYPTION_TRANSPORT)
#define SO_SELECT_ERR_QUEUE SYMBOLIC(SO_SELECT_ERR_QUEUE)
#define SO_SNDBUF SYMBOLIC(SO_SNDBUF)
#define SO_SNDBUFFORCE SYMBOLIC(SO_SNDBUFFORCE)
#define SO_SNDLOWAT SYMBOLIC(SO_SNDLOWAT)
#define SO_SNDTIMEO SYMBOLIC(SO_SNDTIMEO)
#define SO_TIMESTAMP SYMBOLIC(SO_TIMESTAMP)
#define SO_TIMESTAMPING SYMBOLIC(SO_TIMESTAMPING)
#define SO_TIMESTAMPNS SYMBOLIC(SO_TIMESTAMPNS)
#define SO_TYPE SYMBOLIC(SO_TYPE)
#define SO_WIFI_STATUS SYMBOLIC(SO_WIFI_STATUS)

#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

hidden extern const long SO_ACCEPTCONN;
hidden extern const long SO_ATTACH_BPF;
hidden extern const long SO_ATTACH_FILTER;
hidden extern const long SO_ATTACH_REUSEPORT_CBPF;
hidden extern const long SO_ATTACH_REUSEPORT_EBPF;
hidden extern const long SO_BINDTODEVICE;
hidden extern const long SO_BPF_EXTENSIONS;
hidden extern const long SO_BROADCAST;
hidden extern const long SO_BSDCOMPAT;
hidden extern const long SO_BUSY_POLL;
hidden extern const long SO_CNX_ADVICE;
hidden extern const long SO_DEBUG;
hidden extern const long SO_DETACH_BPF;
hidden extern const long SO_DETACH_FILTER;
hidden extern const long SO_DOMAIN;
hidden extern const long SO_DONTROUTE;
hidden extern const long SO_ERROR;
hidden extern const long SO_EXCLUSIVEADDRUSE;
hidden extern const long SO_GET_FILTER;
hidden extern const long SO_INCOMING_CPU;
hidden extern const long SO_KEEPALIVE;
hidden extern const long SO_LINGER;
hidden extern const long SO_LOCK_FILTER;
hidden extern const long SO_MARK;
hidden extern const long SO_MAX_PACING_RATE;
hidden extern const long SO_NOFCS;
hidden extern const long SO_NO_CHECK;
hidden extern const long SO_OOBINLINE;
hidden extern const long SO_PASSCRED;
hidden extern const long SO_PASSSEC;
hidden extern const long SO_PEEK_OFF;
hidden extern const long SO_PEERCRED;
hidden extern const long SO_PEERNAME;
hidden extern const long SO_PEERSEC;
hidden extern const long SO_PRIORITY;
hidden extern const long SO_PROTOCOL;
hidden extern const long SO_RCVBUF;
hidden extern const long SO_RCVBUFFORCE;
hidden extern const long SO_RCVLOWAT;
hidden extern const long SO_RCVTIMEO;
hidden extern const long SO_REUSEADDR;
hidden extern const long SO_REUSEPORT;
hidden extern const long SO_RXQ_OVFL;
hidden extern const long SO_SECURITY_AUTHENTICATION;
hidden extern const long SO_SECURITY_ENCRYPTION_NETWORK;
hidden extern const long SO_SECURITY_ENCRYPTION_TRANSPORT;
hidden extern const long SO_SELECT_ERR_QUEUE;
hidden extern const long SO_SNDBUF;
hidden extern const long SO_SNDBUFFORCE;
hidden extern const long SO_SNDLOWAT;
hidden extern const long SO_SNDTIMEO;
hidden extern const long SO_TIMESTAMP;
hidden extern const long SO_TIMESTAMPING;
hidden extern const long SO_TIMESTAMPNS;
hidden extern const long SO_TYPE;
hidden extern const long SO_WIFI_STATUS;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_SO_H_ */
