#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_SPLICE_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_SPLICE_H_
COSMOPOLITAN_C_START_

extern const unsigned int SPLICE_F_GIFT;
extern const unsigned int SPLICE_F_MORE;
extern const unsigned int SPLICE_F_MOVE;
extern const unsigned int SPLICE_F_NONBLOCK;

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_SPLICE_H_ */
