#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_UC_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_UC_H_
#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

#define UC_FP_XSTATE         1
#define UC_SIGCONTEXT_SS     2
#define UC_STRICT_RESTORE_SS 4

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_UC_H_ */
