#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_MOUNT_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_MOUNT_H_
COSMOPOLITAN_C_START_

extern const int MNT_FORCE;
extern const int MNT_DETACH;
extern const int MNT_EXPIRE;
extern const int UMOUNT_NOFOLLOW;
extern const int MNT_BYFSID;

COSMOPOLITAN_C_END_

#define MNT_FORCE       MNT_FORCE
#define MNT_DETACH      MNT_DETACH
#define MNT_EXPIRE      MNT_EXPIRE
#define UMOUNT_NOFOLLOW UMOUNT_NOFOLLOW
#define MNT_BYFSID      MNT_BYFSID

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_MOUNT_H_ */
