#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_UTIME_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_UTIME_H_
COSMOPOLITAN_C_START_

extern const int UTIME_NOW;
extern const int UTIME_OMIT;

COSMOPOLITAN_C_END_

#define UTIME_NOW  UTIME_NOW
#define UTIME_OMIT UTIME_OMIT


#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_UTIME_H_ */
