#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_UTIME_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_UTIME_H_
#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const int UTIME_NOW;
extern const int UTIME_OMIT;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */

#define UTIME_NOW  UTIME_NOW
#define UTIME_OMIT UTIME_OMIT

#define __tmpcosmo_UTIME_NOW  -1726174975
#define __tmpcosmo_UTIME_OMIT 815598978

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_UTIME_H_ */
