#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_W_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_W_H_
COSMOPOLITAN_C_START_

extern const int WCONTINUED;

#define WNOHANG   1
#define WUNTRACED 2

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_W_H_ */
