#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_XOPEN_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_XOPEN_H_

#define _XOPEN_IOV_MAX  16
#define _XOPEN_ENH_I18N 1
#define _XOPEN_UNIX     1
#define _XOPEN_NAME_MAX 63
#define _XOPEN_PATH_MAX 1024
#define _XOPEN_SOURCE   700

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_XOPEN_H_ */
