#ifndef COSMOPOLITAN_LIBC_RAND_INTERNAL_H_
#define COSMOPOLITAN_LIBC_RAND_INTERNAL_H_
#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

hidden extern uint64_t g_rando;

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_LIBC_RAND_INTERNAL_H_ */
