#ifndef COSMOPOLITAN_LIBC_PROC_VFORK_INTERNAL_H_
#define COSMOPOLITAN_LIBC_PROC_VFORK_INTERNAL_H_
COSMOPOLITAN_C_START_

int __has_vfork(void);

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_PROC_VFORK_INTERNAL_H_ */
