#ifndef COSMOPOLITAN_LIBC_FMT_INTERNAL_H_
#define COSMOPOLITAN_LIBC_FMT_INTERNAL_H_

#define FLAGS_ZEROPAD   0x01
#define FLAGS_LEFT      0x02
#define FLAGS_PLUS      0x04
#define FLAGS_SPACE     0x08
#define FLAGS_HASH      0x10
#define FLAGS_PRECISION 0x20
#define FLAGS_ISSIGNED  0x40
#define FLAGS_NOQUOTE   0x80
#define FLAGS_QUOTE     FLAGS_SPACE
#define FLAGS_GROUPING  FLAGS_NOQUOTE
#define FLAGS_REPR      FLAGS_PLUS

#endif /* COSMOPOLITAN_LIBC_FMT_INTERNAL_H_ */
