#ifndef COSMOPOLITAN_NET_HTTPS_FETCH_H_
#define COSMOPOLITAN_NET_HTTPS_FETCH_H_
COSMOPOLITAN_C_START_

int AppendFetch(char **, const char *);

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_NET_HTTPS_FETCH_H_ */
