#ifndef COSMOPOLITAN_LIBC_ISYSTEM_SYS_TTYDEFAULTS_H_
#define COSMOPOLITAN_LIBC_ISYSTEM_SYS_TTYDEFAULTS_H_
#include "libc/calls/ttydefaults.h"
#endif /* COSMOPOLITAN_LIBC_ISYSTEM_SYS_TTYDEFAULTS_H_ */
