#ifndef COSMOPOLITAN_DSP_TTY_XTERMNAME_H_
#define COSMOPOLITAN_DSP_TTY_XTERMNAME_H_
COSMOPOLITAN_C_START_

extern const char kXtermName[];

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_DSP_TTY_XTERMNAME_H_ */
