#ifndef COSMOPOLITAN_TOOL_VIZ_LIB_HALFBLIT_H_
#define COSMOPOLITAN_TOOL_VIZ_LIB_HALFBLIT_H_
COSMOPOLITAN_C_START_

void *halfblit(size_t, void *);

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_TOOL_VIZ_LIB_HALFBLIT_H_ */
