#ifndef COSMOPOLITAN_TOOL_VIZ_LIB_HALFBLIT_H_
#define COSMOPOLITAN_TOOL_VIZ_LIB_HALFBLIT_H_
#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

void *halfblit(size_t, void *);

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_TOOL_VIZ_LIB_HALFBLIT_H_ */
