#ifndef COSMOPOLITAN_LIBC_ISYSTEM_CPUID_INTERNAL_H_
#define COSMOPOLITAN_LIBC_ISYSTEM_CPUID_INTERNAL_H_
#include "third_party/intel/cpuid.internal.h"
#endif /* COSMOPOLITAN_LIBC_ISYSTEM_CPUID_INTERNAL_H_ */
