#ifndef COSMOPOLITAN_LIBC_ISYSTEM_MM3DNOW_INTERNAL_H_
#define COSMOPOLITAN_LIBC_ISYSTEM_MM3DNOW_INTERNAL_H_
#include "third_party/intel/mm3dnow.internal.h"
#endif /* COSMOPOLITAN_LIBC_ISYSTEM_MM3DNOW_INTERNAL_H_ */
