#ifndef COSMOPOLITAN_TOOL_ARGS_ARGS_H_
#define COSMOPOLITAN_TOOL_ARGS_ARGS_H_
#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

int LoadZipArgs(int *, char ***);

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_TOOL_ARGS_ARGS_H_ */
