#ifndef COSMOPOLITAN_TOOL_ARGS_ARGS_H_
#define COSMOPOLITAN_TOOL_ARGS_ARGS_H_
COSMOPOLITAN_C_START_

int LoadZipArgs(int *, char ***);

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_TOOL_ARGS_ARGS_H_ */
