#ifndef COSMOPOLITAN_LIBC_TINYMATH_ATAN_DATA_H_
#define COSMOPOLITAN_LIBC_TINYMATH_ATAN_DATA_H_
COSMOPOLITAN_C_START_

#define ATAN_POLY_NCOEFFS 20
extern const struct atan_poly_data {
  double poly[ATAN_POLY_NCOEFFS];
} __atan_poly_data;

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_TINYMATH_ATAN_DATA_H_ */
