/*-*- mode:unix-assembly; indent-tabs-mode:t; tab-width:8; coding:utf-8     -*-│
│vi: set et ft=asm ts=8 tw=8 fenc=utf-8                                     :vi│
╞══════════════════════════════════════════════════════════════════════════════╡
│ Copyright 2020 Justine Alexandra Roberts Tunney                              │
│                                                                              │
│ Permission to use, copy, modify, and/or distribute this software for         │
│ any purpose with or without fee is hereby granted, provided that the         │
│ above copyright notice and this permission notice appear in all copies.      │
│                                                                              │
│ THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL                │
│ WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED                │
│ WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE             │
│ AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL         │
│ DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR        │
│ PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER               │
│ TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR             │
│ PERFORMANCE OF THIS SOFTWARE.                                                │
╚─────────────────────────────────────────────────────────────────────────────*/
#include "libc/macros.internal.h"

//	Returns 𝑥 with same sign as 𝑦.
//
//	@param	𝑦 is float scalar in low quarter of %xmm0
//	@param	𝑥 is float scalar in low quarter of %xmm1
//	@return	float scalar in low quarter of %xmm0
copysignf:
	.leafprologue
	.profilable
	movaps	%xmm1,%xmm2
	andps	.LC8(%rip),%xmm0
	andps	.LC10(%rip),%xmm2
	orps	%xmm2,%xmm0
	.leafepilogue
	.endfn	copysignf,globl

	.rodata.cst16
.LC8:	.long	2147483647
	.long	0
	.long	0
	.long	0
.LC10:	.long	2147483648
	.long	0
	.long	0
	.long	0
