#ifndef COSMOPOLITAN_TOOL_NET_LECDSA_H_
#define COSMOPOLITAN_TOOL_NET_LECDSA_H_
#include "third_party/lua/lauxlib.h"
COSMOPOLITAN_C_START_

int LuaECDSA(lua_State *L);

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_TOOL_NET_LECDSA_H_ */
