#ifndef COSMOPOLITAN_TOOL_PLINKO_LIB_KTPENC_H_
#define COSMOPOLITAN_TOOL_PLINKO_LIB_KTPENC_H_
#if !(__ASSEMBLER__ + __LINKER__ + 0)
COSMOPOLITAN_C_START_

extern const short kTpEnc[25];

COSMOPOLITAN_C_END_
#endif /* !(__ASSEMBLER__ + __LINKER__ + 0) */
#endif /* COSMOPOLITAN_TOOL_PLINKO_LIB_KTPENC_H_ */
