#ifndef COSMOPOLITAN_TOOL_PLINKO_LIB_KTPENC_H_
#define COSMOPOLITAN_TOOL_PLINKO_LIB_KTPENC_H_
COSMOPOLITAN_C_START_

extern const short kTpEnc[25];

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_TOOL_PLINKO_LIB_KTPENC_H_ */
