#!/bin/sh
# arm64 backend compiler for fatcosmocc

CC="$COSMO/o/third_party/gcc/bin/aarch64-linux-musl-gcc"
CCFLAGS="-ffixed-x18 -ffixed-x28 -mno-outline-atomics"
LDFLAGS="-static -nostdlib -no-pie -Wl,-z,norelro -Wl,-z,common-page-size=16384 -Wl,-z,max-page-size=16384"
APEFLAGS="-L$COSMOS/lib/.aarch64 -Wl,--gc-sections -Wl,-T,$COSMO/o/$MODE/ape/aarch64.lds"
LDLIBS="$COSMO/o/$MODE/cosmopolitan.a"

if [ x"$PROG" != x"${PROG%++}" ]; then
  CC="$COSMO/o/third_party/gcc/bin/aarch64-linux-musl-g++"
  CCFLAGS="$CCFLAGS -fno-rtti -fno-exceptions -fuse-cxa-atexit"
  LDLIBS="$COSMO/o/$MODE/third_party/libcxx/libcxx.a $LDLIBS"
fi

log_command() {
  if [ -n "$BUILDLOG" ]; then
    printf '# %s\n(cd %s; %s)\n' "$ORIGINAL" "$PWD" "$*" >>"$BUILDLOG"
  fi
}

OPT=
FIRST=1
OUTPUT=
INTENT=ld
for x; do
  if [ $FIRST -eq 1 ]; then
    set --
    FIRST=0
  fi
  if [ x"$x" != x"${x#-O}" ]; then
    OPT=$x
  elif [ x"$x" = x"-c" ]; then
    INTENT=cc
  elif [ x"$x" != x"${x#-o}" ]; then
    OUTPUT=${x#-o}
  elif [ x"$x" != x"${x#-L}" ]; then
    x="$x/.aarch64"
  elif [ x"$x" = x"-march=native" ]; then
    continue  # doesn't make sense for a cross compiler
  fi
  set -- "$@" "$x"
done

if [ x"$OPT" != x"-Os" ] &&                # $OPT != -Os
   [ x"${MODE%tiny}" = x"${MODE}" ]; then  # $MODE not in (tiny, aarch64-tiny)
  # support --ftrace unless optimizing for size
  CCFLAGS="$CCFLAGS -fpatchable-function-entry=7,6"
fi

if [ $INTENT = cc ]; then
  set -- \
      "$CC" \
      $CCFLAGS \
      "$@"
else
  set -- \
      "$CC" \
      "$COSMO/o/$MODE/libc/crt/crt.o" \
      "$@" \
      $LDFLAGS \
      $APEFLAGS \
      $LDLIBS
fi

log_command "$@"
"$@" || exit
"$FIXUPOBJ" "$OUTPUT" || exit
