#!/bin/sh
exec grep                       \
     --exclude=TAGS             \
     --exclude=HTAGS            \
     --exclude=*.com            \
     --exclude-dir=o            \
     --exclude-dir=gcc          \
     --exclude-dir=.git         \
     --exclude=archive-contents \
     "$@"
