#!/bin/sh

COSMOS=${COSMOS:-/opt/cosmos}

for arch in "" .aarch64/; do
  if [ ! -d "$COSMOS/lib/${arch}" ]; then
    mkdir -p "$COSMOS/lib/${arch}"
  fi
  for lib in c dl gcc_s m pthread resolv rt dl z stdc++; do
    if [ ! -f "$COSMOS/lib/${arch}lib${lib}.a" ]; then
      printf '\041\074\141\162\143\150\076\012' >"$COSMOS/lib/${arch}lib${lib}.a"
    fi
  done
done
