#ifndef COSMOPOLITAN_LIBC_NT_TYPEDEF_WNDENUMPROC_H_
#define COSMOPOLITAN_LIBC_NT_TYPEDEF_WNDENUMPROC_H_

typedef int (*NtWndEnumProc)(int64_t foo, intptr_t bar);

#endif /* COSMOPOLITAN_LIBC_NT_TYPEDEF_WNDENUMPROC_H_ */
