#ifndef COSMOPOLITAN_LIBC_NT_ENUM_IMPORTOBJECTTYPE_H_
#define COSMOPOLITAN_LIBC_NT_ENUM_IMPORTOBJECTTYPE_H_

enum NtImportObjectType {
  IMPORT_OBJECT_CODE,
  IMPORT_OBJECT_DATA,
  IMPORT_OBJECT_CONST
};

#endif /* COSMOPOLITAN_LIBC_NT_ENUM_IMPORTOBJECTTYPE_H_ */
