#ifndef COSMOPOLITAN_LIBC_NT_ENUM_PSEUDOCONSOLE_H_
#define COSMOPOLITAN_LIBC_NT_ENUM_PSEUDOCONSOLE_H_

#define kNtPseudoconsoleInheritCursor 1

#endif /* COSMOPOLITAN_LIBC_NT_ENUM_PSEUDOCONSOLE_H_ */
