#ifndef COSMOPOLITAN_LIBC_NT_ENUM_SECTIONINHERIT_H_
#define COSMOPOLITAN_LIBC_NT_ENUM_SECTIONINHERIT_H_

enum NtSectionInherit { kNtViewShare = 1, kNtViewUnmap = 2 };

#endif /* COSMOPOLITAN_LIBC_NT_ENUM_SECTIONINHERIT_H_ */
